### ISSUE TITLE
Sometimes the character doesn't move

### ISSUE THREAD

**Issue by Geromo94** [CipherKill/ValorantFarmer#2]
The game system sees that the player is AFK and does not give experience points

**Comment by ReptilianPride** [comment]
Refer this video (timestamps in the description). If there is still an issue let me know here. :)
Link: https://www.youtube.com/watch?v=f3n5_-peANc&t=55s
Disclaimer: Video may be cringe. But explains how to use the program.

**Comment by CipherKill** [comment]
https://www.youtube.com/watch?v=f3n5_-peANc&t=55s

**Comment by Geromo94** [comment]
Hello, test your script. After end deathmatch you cant get EXP and take attention to AFK. I test now
