### ISSUE TITLE
Perma Suspension

### ISSUE THREAD

**Issue by OompaLoempiaa** [CipherKill/ValorantFarmer#4]
I used this for one game and I instantly got permanently suspended after 20 minutes

![image](https://github.com/CipherKill/ValorantFarmer/assets/163043935/a4fd47f4-25ba-403e-9ca3-92c5fece6495)

**Comment by ReptilianPride** [comment]
Interesting! I'll definitely check it out. I used this method to unlock all my operators in the game. It's been a while since I played Valorant, so it's possible that the game has been updated to counter this.

I'll update the docs accordingly. Thanks for letting me know.
